pipeline:
    projectIdentifier: Kapil
    orgIdentifier: default
    name: aaa
    identifier: abc
    stages:
        - stage:
              name: testll
              identifier: test_lol
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: test
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                  infrastructure:
                      environmentRef: fdsggg
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: asdddd
                              namespace: l
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
