pipeline:
    name: ASDAS
    identifier: ASDAS
    projectIdentifier: Kapil
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: sdfsdf
              identifier: sdfsdf
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              manifestOverrideSets: []
                              manifests: []
                              artifacts:
                                  sidecars: []
                              variables: []
                      serviceRef: <+input>
                  infrastructure:
                      environmentRef: qa
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.trtrtr
                              namespace: asd
                              releaseName: asd
                      allowSimultaneousDeployments: false
                      infrastructureKey: asd
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                          - step:
                                type: Http
                                name: Some Step
                                identifier: S
                                spec:
                                    url: <+input>
                                    method: GET
                                    headers: []
                                    outputVariables: []
                                    requestBody: <+input>
                                timeout: 10s
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
    description: Test
