pipeline:
    name: DemoPipeline
    identifier: DemoPipeline
    projectIdentifier: Kapil
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Stage1
              identifier: Stage1
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              manifestOverrideSets: []
                              manifests: []
                              artifacts:
                                  sidecars: []
                      serviceRef: asd
                  infrastructure:
                      environmentRef: qa
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.k8sqatarget
                              namespace: default
                              releaseName: latest
                      allowSimultaneousDeployments: false
                      infrastructureKey: ""
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: step
                                identifier: step
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: exit 1
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                                failureStrategies:
                                    - onFailure:
                                          action:
                                              type: Ignore
                                          errors:
                                              - AllErrors
                          - step:
                                type: ShellScript
                                name: Step2
                                identifier: Step2
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo 10
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
        - stage:
              name: Failed Stage
              identifier: Failed_Stage
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              manifestOverrideSets: []
                              manifests: []
                              artifacts:
                                  sidecars: []
                      serviceRef: asd
                  infrastructure:
                      environmentRef: qa
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: account.k8sqatarget
                              namespace: default
                              releaseName: asd
                      allowSimultaneousDeployments: false
                      infrastructureKey: ""
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: Step
                                identifier: Step
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: exit 1
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: Ignore
