pipeline:
  name: Eric Git Sync
  identifier: Eric_Git_Sync
  projectIdentifier: Kapil
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: stg1
        identifier: stg1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: stp1
                  identifier: stp1
                  spec:
                    url: <+input>
                    headers: []
                    outputVariables: []
                    requestBody: <+input>
                    method: GET
                  timeout: 10m
        tags: {}
