pipeline:
    name: ParallStage
    identifier: ParallStage
    projectIdentifier: Kapil
    orgIdentifier: default
    tags: {}
    stages:
        - parallel:
              - stage:
                    name: Stage 1
                    identifier: Stage_1
                    description: ""
                    type: Deployment
                    spec:
                        serviceConfig:
                            serviceRef: web
                            serviceDefinition:
                                type: Kubernetes
                                spec:
                                    variables: []
                        infrastructure:
                            environmentRef: fdsggg
                            infrastructureDefinition:
                                type: KubernetesDirect
                                spec:
                                    connectorRef: asdddd
                                    namespace: default
                                    releaseName: release-<+INFRA_KEY>
                            allowSimultaneousDeployments: false
                        execution:
                            steps:
                                - step:
                                      type: ShellScript
                                      name: Test
                                      identifier: Test
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: <+input>
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
                            rollbackSteps: []
                    tags: {}
                    failureStrategies:
                        - onFailure:
                              errors:
                                  - AllErrors
                              action:
                                  type: StageRollback
              - stage:
                    name: Stage 2
                    identifier: Stage_2
                    description: ""
                    type: Deployment
                    spec:
                        serviceConfig:
                            serviceRef: test
                            serviceDefinition:
                                type: Kubernetes
                                spec:
                                    variables: []
                        infrastructure:
                            environmentRef: prod_environment
                            infrastructureDefinition:
                                type: KubernetesDirect
                                spec:
                                    connectorRef: test1111
                                    namespace: deasd
                                    releaseName: release-<+INFRA_KEY>
                            allowSimultaneousDeployments: false
                        execution:
                            steps:
                                - step:
                                      type: ShellScript
                                      name: test
                                      identifier: test
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: <+input>
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
                            rollbackSteps: []
                    tags: {}
                    failureStrategies:
                        - onFailure:
                              errors:
                                  - AllErrors
                              action:
                                  type: StageRollback
              - stage:
                    name: Stage 3
                    identifier: Stage_3
                    description: ""
                    type: Deployment
                    spec:
                        serviceConfig:
                            serviceRef: Very_Big_Service_Name_Really
                            serviceDefinition:
                                type: Kubernetes
                                spec:
                                    variables: []
                        infrastructure:
                            environmentRef: asdasd
                            infrastructureDefinition:
                                type: KubernetesDirect
                                spec:
                                    connectorRef: test1111
                                    namespace: default
                                    releaseName: release-<+INFRA_KEY>
                            allowSimultaneousDeployments: false
                        execution:
                            steps:
                                - step:
                                      type: ShellScript
                                      name: Ssdfsd
                                      identifier: Ssdfsd
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: echo 1
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
                            rollbackSteps: []
                    tags: {}
                    failureStrategies:
                        - onFailure:
                              errors:
                                  - AllErrors
                              action:
                                  type: StageRollback
              - stage:
                    name: Stage 5
                    identifier: Stage_5
                    description: ""
                    type: Deployment
                    spec:
                        serviceConfig:
                            serviceRef: Normal_Service
                            serviceDefinition:
                                type: Kubernetes
                                spec:
                                    variables: []
                        infrastructure:
                            environmentRef: Devsf
                            infrastructureDefinition:
                                type: KubernetesDirect
                                spec:
                                    connectorRef: test1111
                                    namespace: default
                                    releaseName: release-<+INFRA_KEY>
                            allowSimultaneousDeployments: false
                        execution:
                            steps:
                                - step:
                                      type: ShellScript
                                      name: Stepsa
                                      identifier: Stepsa
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: echo 1
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
                                - step:
                                      type: HarnessApproval
                                      name: test
                                      identifier: test
                                      spec:
                                          approvalMessage: Please review the following information and approve the pipeline progression
                                          includePipelineExecutionHistory: true
                                          approvers:
                                              userGroups:
                                                  - test
                                              minimumCount: 1
                                              disallowPipelineExecutor: false
                                          approverInputs: []
                                      timeout: 1d
                            rollbackSteps: []
                    tags: {}
                    failureStrategies:
                        - onFailure:
                              errors:
                                  - AllErrors
                              action:
                                  type: StageRollback
              - stage:
                    name: Stage 6
                    identifier: Stage_6
                    description: ""
                    type: Deployment
                    spec:
                        serviceConfig:
                            serviceRef: Newdds
                            serviceDefinition:
                                type: Kubernetes
                                spec:
                                    variables: []
                        infrastructure:
                            environmentRef: test
                            infrastructureDefinition:
                                type: KubernetesDirect
                                spec:
                                    connectorRef: test1111
                                    namespace: default
                                    releaseName: release-<+INFRA_KEY>
                            allowSimultaneousDeployments: false
                        execution:
                            steps:
                                - step:
                                      type: ShellScript
                                      name: Step 3
                                      identifier: Step_3
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: echo 2
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
                            rollbackSteps: []
                    tags: {}
                    failureStrategies:
                        - onFailure:
                              errors:
                                  - AllErrors
                              action:
                                  type: StageRollback
              - stage:
                    name: Stage 4
                    identifier: Stage_4
                    description: ""
                    type: Deployment
                    spec:
                        serviceConfig:
                            serviceRef: gfgfgf
                            serviceDefinition:
                                type: Kubernetes
                                spec:
                                    variables: []
                        infrastructure:
                            environmentRef: Very_Long_Env_asd_asd_asd_Kapil
                            infrastructureDefinition:
                                type: KubernetesDirect
                                spec:
                                    connectorRef: test1111
                                    namespace: default
                                    releaseName: release-<+INFRA_KEY>
                            allowSimultaneousDeployments: false
                        execution:
                            steps:
                                - step:
                                      type: ShellScript
                                      name: Step asd
                                      identifier: Step_asd
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: echo 1
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
                            rollbackSteps: []
                    tags: {}
                    failureStrategies:
                        - onFailure:
                              errors:
                                  - AllErrors
                              action:
                                  type: StageRollback
