pipeline:
    name: Roll Back Pipeline
    identifier: Roll_Back_Pipeline
    projectIdentifier: Kapil
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: Test Pipeline
              identifier: Test_Pipeline
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: <+input>
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables: []
                  infrastructure:
                      environmentRef: prod_environment
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: test1111
                              namespace: default
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: SH1
                                identifier: SH1
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo 1
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                          - parallel:
                                - stepGroup:
                                      name: Test SG
                                      identifier: Test_SG
                                      steps:
                                          - parallel:
                                                - step:
                                                      type: ShellScript
                                                      name: SH2
                                                      identifier: SH2
                                                      spec:
                                                          shell: Bash
                                                          onDelegate: true
                                                          source:
                                                              type: Inline
                                                              spec:
                                                                  script: echo 2
                                                          environmentVariables: []
                                                          outputVariables: []
                                                          executionTarget: {}
                                                      timeout: 10m
                                                - step:
                                                      type: ShellScript
                                                      name: SH3
                                                      identifier: SH3
                                                      spec:
                                                          shell: Bash
                                                          onDelegate: true
                                                          source:
                                                              type: Inline
                                                              spec:
                                                                  script: echo 3
                                                          environmentVariables: []
                                                          outputVariables: []
                                                          executionTarget: {}
                                                      timeout: 10m
                                      failureStrategies: []
                                      spec:
                                          delegateSelectors: <+input>
                                - step:
                                      type: ShellScript
                                      name: SH4
                                      identifier: SH4
                                      spec:
                                          shell: Bash
                                          onDelegate: true
                                          source:
                                              type: Inline
                                              spec:
                                                  script: echo 4
                                          environmentVariables: []
                                          outputVariables: []
                                          executionTarget: {}
                                      timeout: 10m
                          - step:
                                type: ShellScript
                                name: SH5
                                identifier: SH5
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo 5
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                          - step:
                                type: ShellScript
                                name: SH Failed
                                identifier: SH_Failed
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: |-
                                                echo 23
                                                exit 1
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps:
                          - step:
                                type: ShellScript
                                name: Failure QQ
                                identifier: Failure_QQ
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo 2
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                  serviceDependencies: []
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
              delegateSelectors:
                  - <+input>
    delegateSelectors:
        - <+input>
