pipeline:
    name: Variable Demo
    identifier: Variable_Demo
    projectIdentifier: Kapil
    orgIdentifier: default
    description: Test Description
    tags: {}
    stages:
        - stage:
              name: Stage Name
              identifier: Stage_Name
              description: Stage Variables
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: test
                      serviceDefinition:
                          type: Kubernetes
                          spec:
                              variables:
                                  - name: ServiceVar1
                                    type: String
                                    value: <+pipeline.description>
                  infrastructure:
                      environmentRef: prod_environment
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: Test222
                              namespace: default
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                type: ShellScript
                                name: Test
                                identifier: Test
                                spec:
                                    shell: Bash
                                    onDelegate: true
                                    source:
                                        type: Inline
                                        spec:
                                            script: echo <+pipeline.variables.Test1>
                                    environmentVariables: []
                                    outputVariables: []
                                    executionTarget: {}
                                timeout: 10m
                      rollbackSteps: []
              tags: {}
              variables:
                  - name: Stage1
                    type: String
                    default: test
                    value: <+input>.allowedValues(test,test1)
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
    variables:
        - name: Test1
          type: String
          value: <+input>
